//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeonameAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GeonameAPIContextEntities : DbContext
    {
        public GeonameAPIContextEntities()
            : base("name=GeonameAPIContextEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GeoName> GeoNames { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
    
        public virtual ObjectResult<GeoName> GetSuggestedCities(string term)
        {
            var termParameter = term != null ?
                new ObjectParameter("term", term) :
                new ObjectParameter("term", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GeoName>("GetSuggestedCities", termParameter);
        }
    
        public virtual ObjectResult<GeoName> GetSuggestedCities(string term, MergeOption mergeOption)
        {
            var termParameter = term != null ?
                new ObjectParameter("term", term) :
                new ObjectParameter("term", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GeoName>("GetSuggestedCities", mergeOption, termParameter);
        }
    }
}
