// <auto-generated />
namespace GeonameAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class spGetCities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(spGetCities));
        
        string IMigrationMetadata.Id
        {
            get { return "202007031809430_sp-GetCities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
